# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 644)
        self.main_widget = QtWidgets.QWidget(MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.middle_line = QtWidgets.QSplitter(self.main_widget)
        self.middle_line.setGeometry(QtCore.QRect(10, 10, 921, 531))
        self.middle_line.setOrientation(QtCore.Qt.Horizontal)
        self.middle_line.setObjectName("middle_line")
        self.group_sort = QtWidgets.QGroupBox(self.middle_line)
        self.group_sort.setObjectName("group_sort")
        self.label_sort_col_names = QtWidgets.QLabel(self.group_sort)
        self.label_sort_col_names.setGeometry(QtCore.QRect(21, 31, 72, 18))
        self.label_sort_col_names.setObjectName("label_sort_col_names")
        self.combo_sort_col_names = QtWidgets.QComboBox(self.group_sort)
        self.combo_sort_col_names.setGeometry(QtCore.QRect(130, 30, 281, 24))
        self.combo_sort_col_names.setObjectName("combo_sort_col_names")
        self.sort_radio_asc = QtWidgets.QRadioButton(self.group_sort)
        self.sort_radio_asc.setGeometry(QtCore.QRect(180, 60, 61, 19))
        self.sort_radio_asc.setObjectName("sort_radio_asc")
        self.sort_radio_desc = QtWidgets.QRadioButton(self.group_sort)
        self.sort_radio_desc.setGeometry(QtCore.QRect(290, 60, 61, 19))
        self.sort_radio_desc.setObjectName("sort_radio_desc")
        self.label_sort_sex = QtWidgets.QLabel(self.group_sort)
        self.label_sort_sex.setGeometry(QtCore.QRect(20, 90, 101, 16))
        self.label_sort_sex.setObjectName("label_sort_sex")
        self.sort_radio_female = QtWidgets.QRadioButton(self.group_sort)
        self.sort_radio_female.setGeometry(QtCore.QRect(230, 90, 81, 19))
        self.sort_radio_female.setObjectName("sort_radio_female")
        self.sort_radio_male = QtWidgets.QRadioButton(self.group_sort)
        self.sort_radio_male.setGeometry(QtCore.QRect(130, 90, 61, 19))
        self.sort_radio_male.setObjectName("sort_radio_male")
        self.sort_radio_all = QtWidgets.QRadioButton(self.group_sort)
        self.sort_radio_all.setGeometry(QtCore.QRect(350, 90, 81, 19))
        self.sort_radio_all.setObjectName("sort_radio_all")
        self.label_3 = QtWidgets.QLabel(self.group_sort)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 72, 15))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_sort_names = QtWidgets.QLabel(self.group_sort)
        self.label_sort_names.setGeometry(QtCore.QRect(20, 130, 151, 16))
        self.label_sort_names.setObjectName("label_sort_names")
        self.lineedit_sort_names = QtWidgets.QLineEdit(self.group_sort)
        self.lineedit_sort_names.setGeometry(QtCore.QRect(130, 130, 281, 21))
        self.lineedit_sort_names.setObjectName("lineedit_sort_names")
        self.tbl_view_show_data = QtWidgets.QTableView(self.group_sort)
        self.tbl_view_show_data.setGeometry(QtCore.QRect(10, 160, 401, 351))
        self.tbl_view_show_data.setObjectName("tbl_view_show_data")
        self.group_info = QtWidgets.QGroupBox(self.middle_line)
        self.group_info.setObjectName("group_info")
        self.widget = QtWidgets.QWidget(self.group_info)
        self.widget.setGeometry(QtCore.QRect(30, 30, 411, 481))
        self.widget.setObjectName("widget")
        self.layout_grid_info = QtWidgets.QGridLayout(self.widget)
        self.layout_grid_info.setContentsMargins(0, 0, 0, 0)
        self.layout_grid_info.setObjectName("layout_grid_info")
        self.label_info_id = QtWidgets.QLabel(self.widget)
        self.label_info_id.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_id.setObjectName("label_info_id")
        self.layout_grid_info.addWidget(self.label_info_id, 0, 0, 1, 1)
        self.textedit_memo = QtWidgets.QPlainTextEdit(self.widget)
        self.textedit_memo.setObjectName("textedit_memo")
        self.layout_grid_info.addWidget(self.textedit_memo, 9, 1, 1, 2)
        self.label_info_memo = QtWidgets.QLabel(self.widget)
        self.label_info_memo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_memo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_memo.setObjectName("label_info_memo")
        self.layout_grid_info.addWidget(self.label_info_memo, 9, 0, 1, 1)
        self.combo_info_birth_addr = QtWidgets.QComboBox(self.widget)
        self.combo_info_birth_addr.setObjectName("combo_info_birth_addr")
        self.layout_grid_info.addWidget(self.combo_info_birth_addr, 4, 1, 1, 2)
        self.combo_info_salary = QtWidgets.QComboBox(self.widget)
        self.combo_info_salary.setObjectName("combo_info_salary")
        self.layout_grid_info.addWidget(self.combo_info_salary, 8, 1, 1, 2)
        self.spin_info_id = QtWidgets.QSpinBox(self.widget)
        self.spin_info_id.setObjectName("spin_info_id")
        self.layout_grid_info.addWidget(self.spin_info_id, 0, 1, 1, 2)
        self.combo_info_sex = QtWidgets.QComboBox(self.widget)
        self.combo_info_sex.setObjectName("combo_info_sex")
        self.layout_grid_info.addWidget(self.combo_info_sex, 2, 1, 1, 2)
        self.label_info_name = QtWidgets.QLabel(self.widget)
        self.label_info_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_name.setObjectName("label_info_name")
        self.layout_grid_info.addWidget(self.label_info_name, 1, 0, 1, 1)
        self.label_info_salary = QtWidgets.QLabel(self.widget)
        self.label_info_salary.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_salary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_salary.setObjectName("label_info_salary")
        self.layout_grid_info.addWidget(self.label_info_salary, 7, 0, 2, 1)
        self.dateedit_brith_year = QtWidgets.QDateEdit(self.widget)
        self.dateedit_brith_year.setCalendarPopup(True)
        self.dateedit_brith_year.setObjectName("dateedit_brith_year")
        self.layout_grid_info.addWidget(self.dateedit_brith_year, 3, 1, 1, 2)
        self.label_info_birth_year = QtWidgets.QLabel(self.widget)
        self.label_info_birth_year.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_birth_year.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_birth_year.setObjectName("label_info_birth_year")
        self.layout_grid_info.addWidget(self.label_info_birth_year, 3, 0, 1, 1)
        self.lineedit_name = QtWidgets.QLineEdit(self.widget)
        self.lineedit_name.setObjectName("lineedit_name")
        self.layout_grid_info.addWidget(self.lineedit_name, 1, 1, 1, 2)
        self.label_info_sex = QtWidgets.QLabel(self.widget)
        self.label_info_sex.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_sex.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_sex.setObjectName("label_info_sex")
        self.layout_grid_info.addWidget(self.label_info_sex, 2, 0, 1, 1)
        self.label_info_birth_addr = QtWidgets.QLabel(self.widget)
        self.label_info_birth_addr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_birth_addr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_birth_addr.setObjectName("label_info_birth_addr")
        self.layout_grid_info.addWidget(self.label_info_birth_addr, 4, 0, 1, 1)
        self.label_info_dept = QtWidgets.QLabel(self.widget)
        self.label_info_dept.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_info_dept.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info_dept.setObjectName("label_info_dept")
        self.layout_grid_info.addWidget(self.label_info_dept, 5, 0, 1, 1)
        self.combo_info_dept = QtWidgets.QComboBox(self.widget)
        self.combo_info_dept.setObjectName("combo_info_dept")
        self.layout_grid_info.addWidget(self.combo_info_dept, 5, 1, 1, 2)
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_add = QtWidgets.QAction(MainWindow)
        self.act_add.setObjectName("act_add")
        self.act_insert = QtWidgets.QAction(MainWindow)
        self.act_insert.setObjectName("act_insert")
        self.act_del = QtWidgets.QAction(MainWindow)
        self.act_del.setObjectName("act_del")
        self.act_new_photo = QtWidgets.QAction(MainWindow)
        self.act_new_photo.setObjectName("act_new_photo")
        self.act_del_photo = QtWidgets.QAction(MainWindow)
        self.act_del_photo.setObjectName("act_del_photo")
        self.act_save = QtWidgets.QAction(MainWindow)
        self.act_save.setObjectName("act_save")
        self.act_save.setEnabled(False)   # Set the initial Save button to False
        self.act_cancel_change = QtWidgets.QAction(MainWindow)
        self.act_cancel_change.setObjectName("act_cancel_change")
        self.act_cancel_change.setEnabled(False)  # Sete the initial Cancel button to False
        self.act_exit = QtWidgets.QAction(MainWindow)
        self.act_exit.setObjectName("act_exit")
        self.toolBar.addAction(self.act_add)
        self.toolBar.addAction(self.act_insert)
        self.toolBar.addAction(self.act_del)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.act_new_photo)
        self.toolBar.addAction(self.act_del_photo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.act_save)
        self.toolBar.addAction(self.act_cancel_change)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.act_exit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.group_sort.setTitle(_translate("MainWindow", "Sort"))
        self.label_sort_col_names.setText(_translate("MainWindow", "Col Name"))
        self.sort_radio_asc.setText(_translate("MainWindow", "Asc"))
        self.sort_radio_desc.setText(_translate("MainWindow", "Desc"))
        self.label_sort_sex.setText(_translate("MainWindow", "Sort Sex"))
        self.sort_radio_female.setText(_translate("MainWindow", "Female"))
        self.sort_radio_male.setText(_translate("MainWindow", "Male"))
        self.sort_radio_all.setText(_translate("MainWindow", "All"))
        self.label_sort_names.setText(_translate("MainWindow", "Sort Name"))
        self.group_info.setTitle(_translate("MainWindow", "Employee Info"))
        self.label_info_id.setText(_translate("MainWindow", "ID"))
        self.label_info_memo.setText(_translate("MainWindow", "Memo"))
        self.label_info_name.setText(_translate("MainWindow", "Name"))
        self.label_info_salary.setText(_translate("MainWindow", "Salary"))
        self.label_info_birth_year.setText(_translate("MainWindow", "Birth Year"))
        self.label_info_sex.setText(_translate("MainWindow", "Sex"))
        self.label_info_birth_addr.setText(_translate("MainWindow", "Birth Addr"))
        self.label_info_dept.setText(_translate("MainWindow", "Dept"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.act_add.setText(_translate("MainWindow", "Add"))
        self.act_add.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add new line of data</p></body></html>"))
        self.act_insert.setText(_translate("MainWindow", "insert"))
        self.act_insert.setToolTip(_translate("MainWindow", "<html><head/><body><p>insert new line of data into certain location</p><p><br/></p></body></html>"))
        self.act_del.setText(_translate("MainWindow", "del"))
        self.act_del.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delete current line of data</p></body></html>"))
        self.act_new_photo.setText(_translate("MainWindow", "add_photo"))
        self.act_new_photo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Add new image</p></body></html>"))
        self.act_del_photo.setText(_translate("MainWindow", "del_photo"))
        self.act_del_photo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delete current photo</p></body></html>"))
        self.act_save.setText(_translate("MainWindow", "save"))
        self.act_save.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save changes</p><p><br/></p></body></html>"))
        self.act_cancel_change.setText(_translate("MainWindow", "cancel_change"))
        self.act_cancel_change.setToolTip(_translate("MainWindow", "<html><head/><body><p>Cancel changes</p></body></html>"))
        self.act_exit.setText(_translate("MainWindow", "exit"))
        self.act_exit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Quit program</p><p><br/></p></body></html>"))

