# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.unreg_grpbox = QtWidgets.QGroupBox(self.centralwidget)
        self.unreg_grpbox.setGeometry(QtCore.QRect(70, 40, 871, 491))
        self.unreg_grpbox.setObjectName("unreg_grpbox")
        self.widget = QtWidgets.QWidget(self.unreg_grpbox)
        self.widget.setGeometry(QtCore.QRect(168, 70, 301, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unreg_date_start = QtWidgets.QDateEdit(self.widget)
        self.unreg_date_start.setDate(QtCore.QDate.currentDate())
        self.unreg_date_start.setCalendarPopup(True)
        self.unreg_date_start.setObjectName("unreg_date_start")
        self.horizontalLayout.addWidget(self.unreg_date_start)
        self.unreg_date_to = QtWidgets.QLabel(self.widget)
        self.unreg_date_to.setObjectName("unreg_date_to")
        self.horizontalLayout.addWidget(self.unreg_date_to)
        self.unreg_date_end = QtWidgets.QDateEdit(self.widget)
        self.unreg_date_end.setDate(QtCore.QDate.currentDate())
        self.unreg_date_end.setCalendarPopup(True)
        self.unreg_date_end.setObjectName("unreg_date_end")
        self.horizontalLayout.addWidget(self.unreg_date_end)
        self.unreg_search = QtWidgets.QPushButton(self.unreg_grpbox)
        self.unreg_search.setGeometry(QtCore.QRect(580, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.unreg_search.setFont(font)
        self.unreg_search.setObjectName("unreg_search")
        self.unreg_date_label = QtWidgets.QLabel(self.unreg_grpbox)
        self.unreg_date_label.setGeometry(QtCore.QRect(48, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.unreg_date_label.setFont(font)
        self.unreg_date_label.setObjectName("unreg_date_label")
        self.unreg_modification = QtWidgets.QPushButton(self.unreg_grpbox)
        self.unreg_modification.setGeometry(QtCore.QRect(720, 40, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.unreg_modification.setFont(font)
        self.unreg_modification.setObjectName("unreg_modification")
        self.unreg_input = QtWidgets.QLineEdit(self.unreg_grpbox)
        self.unreg_input.setPlaceholderText('请输入门诊号')
        self.unreg_input.setGeometry(QtCore.QRect(168, 30, 301, 21))
        self.unreg_input.setObjectName("unreg_input")
        self.unreg_id_label = QtWidgets.QLabel(self.unreg_grpbox)
        self.unreg_id_label.setGeometry(QtCore.QRect(48, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(12)
        self.unreg_id_label.setFont(font)
        self.unreg_id_label.setObjectName("unreg_id_label")
        self.unreg_table_view = QtWidgets.QTableView(self.unreg_grpbox)
        self.unreg_table_view.setGeometry(QtCore.QRect(20, 110, 831, 361))
        self.unreg_table_view.setObjectName("unreg_table_view")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1013, 26))
        self.menubar.setObjectName("menubar")
        self.menu_db = QtWidgets.QMenu(self.menubar)
        self.menu_db.setObjectName("menu_db")
        self.menu_db_registration = QtWidgets.QMenu(self.menu_db)
        self.menu_db_registration.setObjectName("menu_db_registration")
        self.menu_utilities = QtWidgets.QMenu(self.menubar)
        self.menu_utilities.setObjectName("menu_utilities")
        self.menu_utilities_pharmacy = QtWidgets.QMenu(self.menu_utilities)
        self.menu_utilities_pharmacy.setObjectName("menu_utilities_pharmacy")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_db_unreg = QtWidgets.QAction(MainWindow)
        self.menu_db_unreg.setObjectName("menu_db_unreg")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu_db_quit = QtWidgets.QAction(MainWindow)
        self.menu_db_quit.setObjectName("menu_db_quit")
        self.menu_utilities_pharmacy_swift_save = QtWidgets.QAction(MainWindow)
        self.menu_utilities_pharmacy_swift_save.setObjectName("menu_utilities_pharmacy_swift_save")
        self.menu_help_about = QtWidgets.QAction(MainWindow)
        self.menu_help_about.setObjectName("menu_help_about")
        self.menu_db_registration.addAction(self.menu_db_unreg)
        self.menu_db.addAction(self.menu_db_registration.menuAction())
        self.menu_db.addSeparator()
        self.menu_db.addAction(self.menu_db_quit)
        self.menu_utilities_pharmacy.addAction(self.menu_utilities_pharmacy_swift_save)
        self.menu_utilities.addAction(self.menu_utilities_pharmacy.menuAction())
        self.menu_help.addAction(self.menu_help_about)
        self.menubar.addAction(self.menu_db.menuAction())
        self.menubar.addAction(self.menu_utilities.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "帮助程序"))
        self.unreg_grpbox.setTitle(_translate("MainWindow", "退号处理"))
        self.unreg_date_to.setText(_translate("MainWindow", "   至"))
        self.unreg_search.setText(_translate("MainWindow", "查询"))
        self.unreg_date_label.setText(_translate("MainWindow", "日期"))
        self.unreg_modification.setText(_translate("MainWindow", "修改"))
        self.unreg_id_label.setText(_translate("MainWindow", "门诊号"))
        self.menu_db.setTitle(_translate("MainWindow", "数据操作"))
        self.menu_db_registration.setTitle(_translate("MainWindow", "收费"))
        self.menu_utilities.setTitle(_translate("MainWindow", "工具"))
        self.menu_utilities_pharmacy.setTitle(_translate("MainWindow", "西药房"))
        self.menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.menu_db_unreg.setText(_translate("MainWindow", "退号"))
        self.action_3.setText(_translate("MainWindow", "---"))
        self.menu_db_quit.setText(_translate("MainWindow", "退出"))
        self.menu_utilities_pharmacy_swift_save.setText(_translate("MainWindow", "快速保存"))
        self.menu_help_about.setText(_translate("MainWindow", "关于"))

